services:
  api:
    container_name: remi-test-fe
    image: remi-test-fe-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      # ✨ Target the dev stage
      target: dev
    # Mount host directory to docker container to support watch mode
    volumes:
      - .:/app
      # This ensures that the NestJS container manages the node_modules folder
      # rather than synchronizes it with the host machine
      - /app/node_modules
    # env_file:
    #   - docker.env
    ports:
      - 3000:3000
    command: yarn dev
